"""Private plotting constants for the pqg backend."""

DEFAULT_DPI = 100.0
ANIMATION_FRAME_DRAIN_LIMIT = 100
WINDOWED_QUEUE_DRAIN_LIMIT = 50
LIVE_TIMER_INTERVAL_MS = 10
RELATION_TIMER_INTERVAL_MS = 30
AXIS_MIN_MAGNITUDE = 1.0e-9
AXIS_MAX_ABS_LIMIT = 1.0e9
AXIS_DECAY_FACTOR = 0.995
AXIS_PADDING_FACTOR = 1.08
XY_PADDING_RATIO = 0.1
